name: hitomi
description: A sample command-line application.
version: 1.0.3
homepage: https://github.com/baijunty/hitomi

environment:
  sdk: '>3.8.0'

dependencies: 
  args: ^2.7.0
  test: ^1.28.0
  path: ^1.9.1
  crypto: ^3.0.7
  image: ^4.7.2
  async: ^2.13.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  collection: ^1.19.1
  sqlite3: ^3.1.4
  dio: ^5.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.2
  dcache: ^0.4.0
  logger: ^2.6.2
  isolate_manager: ^6.1.2
  http: ^1.5.0
  ml_linalg: ^13.12.6

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.1
  freezed: ^3.2.3
